### ISSUE TITLE
Error in R_nc4_open: Too many open files

### ISSUE THREAD

**Issue by Kasi21** [dklinges9/mcera5#41] opened 2024-11-07 06:43 UTC
Hi Dave, 

Similar to the issue [here by lysoifer](https://github.com/dklinges9/mcera5/issues/13), I'm getting an _Error in R_nc4_open: Too many open files_ error (full message below) after several iterations of a for loop. See below for a concatenated code example. For context, this is a loop that I've been running as a background job with several other versions of the same code. 

Do you know what the issue might be/ have a fix?

Thanks in advance, and all the best, 

Kas

[Link to .nc file
](https://drive.google.com/file/d/1_sJwz4rllVktjDPHlgO13OPC6qJ0rGVl/view?usp=drive_link)

```

st_time <- as.POSIXlt("2011-07-15 00:00", tz = "UTC")
en_time <- as.POSIXlt("2013-04-22 23:00", tz = "UTC")

loop_lat <- -19.19643
loop_lon <- 23.88476

for (i in 1:1500) { 

  # Extract the climate data from the era5 variables
  hourlyData <- extract_clim(
    nc = 'Data/era5/study_system_2011_05-2013_12.nc', 
    long = loop_lon, 
    lat = loop_lat, 
    start_time = st_time, 
    end_time = en_time, 
    format = 'NicheMapR'
  )  
  
  # Extract the precipitation data from the era5 variables
  rainfallData <- extract_precip(
    nc = 'Data/era5/study_system_2011_05-2013_12.nc', 
    long = loop_lon, 
    lat = loop_lat, 
    start_time = st_time, 
    end_time = en_time 
  )  
  
}


```

**ERROR MESSAGE:**

```
Error in R_nc4_open: Too many open files
Error in ncdf4::nc_open(nc) : 
  Error in nc_open trying to open file Data/era5/study_system_2011_05-2013_12.nc (return_on_error= FALSE )

```

**Comment by dklinges9** [comment] 2024-11-11 15:34
Hi Kas,

Thanks for the notice. I downloaded your netCDF and ran your code here, and was able to make it through a few hundred iterations before the session hung-- but I didn't actually receive the same error message as you, even if the root cause of my session hanging was also because of I/O with the netCDF.

How many iterations were you able to work through before you received this error?

**Comment by Kasi21** [comment] 2024-11-12 09:42
Hi Dave, 

Thanks for checking. I'm not sure exactly how many iterations because I had it running in two different R sessions for a while and it was a few days ago. It was at least several hundred iterations I think.

**Comment by dklinges9** [comment] 2024-11-14 14:13
I'd suggest breaking it up into fewer iterations, and writing objects to disk-- which might work for the best anyways in case there end up being memory limitations in the R environment.

Closing this issue, not because it isn't a problem as it still is, but given that connections to netCDF files are already closed at the end of mcera5 processing, this might be lower level than what's in-scope within the package. But keep me posted if other related problems arise!

**Closed as completed by dklinges9** 2024-11-14 14:13 UTC

**Comment by Kasi21** [comment] 2024-11-14 15:09
Thanks, Dave. I'll make a plan to implement your suggestion. 

Quick question on doing this. Since each of the iterations is running through a full loop of mcera5 processing (i.e., each loop is for the microclimate at a different location in our system) and in my full code I'm already saving every 50 iterations, would changing the iterations alone reduce the likelihood of the issue, or would I need to do a full restart of R (or similar) every x iterations?

Quick note: I also tried including 'close(nc)' within the loop, but it didn't work.

**Comment by dklinges9** [comment] 2024-11-15 00:48
Yes, to clarify: writing to disk isn't going to solve the issue, and probably not reduce the likelihood, but will at least save your outputs-- this would be to avoid lost time/progressing when the R session crashes or hangs.

I'll keep this issue in mind in future debugging and see if I can come across some workaround, if indeed there is any functionality in mcera5 that is related to such crashing/hanging
